import { describe, expect, it } from "vitest";
import { buildInterviewAnswerEvaluationSystemPrompt, INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT } from "./interviewAnswerEvaluationPrompt";

describe("interview answer evaluation prompt", () => {
  it("forbids sensitive-trait scoring and invented facts", () => { expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Never score grammar, accent, name, gender, age, nationality"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Never invent experience"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("never use fabricated placeholders"); });
  it("keeps improvedAnswer within the user's actual answer", () => { expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("The answer is the primary and controlling factual source for improvedAnswer"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Information found only in resumeEvidence must not be inserted into improvedAnswer"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("jdEvidence is evaluation context only"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Do not silently add technologies, motivations, company values, career plans"); });
  it("uses question-appropriate evidence standards", () => { expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Motivation questions: assess whether the motivation is specific"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Behavioral or experience questions"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Technical knowledge questions: assess conceptual correctness"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Technical experience or debugging questions"); });
  it("does not require metrics and accepts qualitative outcomes", () => { expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Do not require quantitative metrics for every answer"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Never encourage the candidate to invent measurements"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Accept concrete qualitative outcomes"); });
  it("only requests one follow-up for a material gap", () => { expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Minor wording, small structural improvements, optional metrics"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("exactly one short, focused question"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("never combine multiple questions"); });
  it("does not force technical questions into STAR or start a follow-up loop", () => { expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Technical knowledge questions must not be forced into STAR"); expect(INTERVIEW_ANSWER_EVALUATION_SYSTEM_PROMPT).toContain("Do not conduct another interview turn"); });
  it.each([["zh-TW", "Traditional Chinese"], ["zh-CN", "Simplified Chinese"], ["en", "English"]] as const)("adds the %s language rule", (locale, expected) => expect(buildInterviewAnswerEvaluationSystemPrompt(locale)).toContain(expected));
});
