import type { AnalysisResult } from "@/types/analysis";

type AnalysisResultPanelProps = {
  result: AnalysisResult;
};

function ResultList({ title, items }: { title: string; items: string[] }) {
  return (
    <article className="rounded-lg border border-zinc-200 bg-white p-5 shadow-sm">
      <h3 className="text-base font-semibold text-zinc-950">{title}</h3>
      <ul className="mt-4 space-y-2 text-sm leading-6 text-zinc-700">
        {items.map((item) => (
          <li key={item} className="flex gap-2">
            <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-700" />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </article>
  );
}

export function AnalysisResultPanel({ result }: AnalysisResultPanelProps) {
  return (
    <section className="grid gap-4">
      <article className="rounded-lg border border-zinc-200 bg-white p-5 shadow-sm">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-sm font-medium uppercase tracking-wide text-zinc-500">
              Phase 1 Mock Preview
            </p>
            <h2 className="mt-1 text-lg font-semibold text-zinc-950">
              Overall Match Score
            </h2>
          </div>
          <p className="max-w-xl text-sm leading-6 text-zinc-600">
            This is fixed mock data and is not generated by the LLM or based on this resume.
          </p>
        </div>
        <div className="mt-3 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
          <p className="text-5xl font-semibold text-zinc-950">{result.matchScore}</p>
          <p className="rounded-md bg-emerald-100 px-3 py-2 text-sm font-semibold text-emerald-800">
            {result.matchLevel}
          </p>
        </div>
      </article>

      <div className="grid gap-4 lg:grid-cols-3">
        <ResultList title="Strengths" items={result.strengths} />
        <ResultList title="Potential Gaps" items={result.potentialGaps} />
        <ResultList title="Likely Interview Focus" items={result.interviewFocus} />
      </div>
    </section>
  );
}
