import type { FormEvent } from "react";
import type { SupportedLocale } from "@/lib/i18n/locales";
import { translate } from "@/lib/i18n/messages";
import { MAX_FOLLOW_UP_ROUNDS } from "@/lib/practice/followUpFlow";
import type { FollowUpTurn } from "@/types/practice";

export function PracticeFollowUpPanel({ locale, history, pendingQuestion, answer, submitting, error, onAnswerChange, onSubmit, onFinish }: { locale: SupportedLocale; history: FollowUpTurn[]; pendingQuestion: string | null; answer: string; submitting: boolean; error: string | null; onAnswerChange: (value: string) => void; onSubmit: () => void; onFinish: () => void }) {
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSubmit(); }
  return <section className="grid gap-4 rounded-lg border border-amber-200 bg-amber-50 p-5">
    {history.map((turn) => <article key={turn.round} className="min-w-0 rounded-md bg-white p-4"><h3 className="font-semibold text-amber-950">{translate(locale, "followUpRound").replace("{round}", String(turn.round)).replace("{max}", String(MAX_FOLLOW_UP_ROUNDS))}</h3><p className="mt-2 break-words text-zinc-800">{turn.question}</p><h4 className="mt-4 text-sm font-semibold text-zinc-600">{translate(locale, "yourFollowUpAnswer")}</h4><p className="mt-2 whitespace-pre-wrap break-words text-zinc-800">{turn.answer}</p></article>)}
    {pendingQuestion ? <form onSubmit={submit} noValidate className="min-w-0 rounded-md bg-white p-4"><h3 className="font-semibold text-amber-950">{translate(locale, "followUpRound").replace("{round}", String(history.length + 1)).replace("{max}", String(MAX_FOLLOW_UP_ROUNDS))}</h3><p className="mt-2 break-words leading-7">{pendingQuestion}</p><label htmlFor="practice-follow-up-answer" className="mt-4 block font-semibold">{translate(locale, "yourFollowUpAnswer")}</label><textarea id="practice-follow-up-answer" value={answer} disabled={submitting} aria-invalid={Boolean(error)} onChange={(event) => onAnswerChange(event.target.value)} placeholder={translate(locale, "followUpAnswerPlaceholder")} className="mt-2 min-h-40 w-full resize-y rounded-md border border-zinc-300 p-3 outline-none focus:border-teal-600 disabled:bg-zinc-100"/><div className="mt-2 flex justify-between gap-3 text-sm">{error ? <p role="alert" className="font-medium text-red-700">{error}</p> : <span/>}<span>{answer.length} / 3000</span></div><div className="mt-4 flex flex-wrap gap-3"><button type="submit" disabled={submitting} className="rounded-md bg-teal-700 px-4 py-2 font-semibold text-white disabled:opacity-60">{translate(locale, submitting ? "evaluatingFollowUp" : "submitFollowUp")}</button><button type="button" disabled={submitting} onClick={onFinish} className="rounded-md border border-zinc-300 px-4 py-2 font-semibold disabled:opacity-60">{translate(locale, "finishQuestion")}</button></div>{submitting ? <p role="status" className="mt-3 text-sm font-medium">{translate(locale, "evaluatingFollowUp")}</p> : null}</form> : null}
  </section>;
}
