import { describe, expect, it, vi } from "vitest";
import { validPreparation } from "@/test/preparationFixture";
import { validFinalEvaluation } from "@/test/followUpEvaluationFixture";
import { buildFollowUpEvaluationRequest, createFollowUpEvaluationRequestController } from "./followUpEvaluationClient";
const success = { success: true as const, data: { decision: "complete" as const, stopReason: "answer_complete" as const, nextFollowUpQuestion: null, finalEvaluation: validFinalEvaluation } };
const history = [{ round: 1, question: "What was the outcome?", answer: "The issue stopped occurring after validation." }];
describe("follow-up evaluation client", () => {
  it("builds only allowlisted fields", () => { const payload = buildFollowUpEvaluationRequest(validPreparation.questions[0], "A sufficiently detailed original interview answer.", history, "en", "continue"); expect(Object.keys(payload).sort()).toEqual(["answerOutline", "category", "difficulty", "followUpHistory", "intent", "jdEvidence", "originalAnswer", "outputLanguage", "question", "relatedRequirement", "resumeEvidence", "whyAsked"].sort()); expect(payload).not.toHaveProperty("resume"); });
  it("sends the full completed history without unrelated workflow data", () => { const fullHistory = [...history, { round: 2, question: "How did you verify it?", answer: "I ran deterministic integration checks." }]; const payload = buildFollowUpEvaluationRequest(validPreparation.questions[0], "A sufficiently detailed original interview answer.", fullHistory, "zh-TW", "continue"); expect(payload.followUpHistory).toEqual(fullHistory); expect(payload).not.toHaveProperty("jobDescription"); expect(payload).not.toHaveProperty("analysis"); expect(payload).not.toHaveProperty("questions"); expect(payload).not.toHaveProperty("reviewTopics"); expect(payload).not.toHaveProperty("apiKey"); });
  it("posts once and blocks a rapid duplicate", async () => { let resolveResponse: ((response: Response) => void) | undefined; const fetcher = vi.fn(() => new Promise<Response>((resolve) => { resolveResponse = resolve; })); const controller = createFollowUpEvaluationRequestController(fetcher); const payload = buildFollowUpEvaluationRequest(validPreparation.questions[0], "A sufficiently detailed original interview answer.", history, "en", "continue"); const first = controller.submit(payload); expect(await controller.submit(payload)).toEqual({ status: "duplicate" }); expect(fetcher).toHaveBeenCalledTimes(1); resolveResponse?.(new Response(JSON.stringify(success))); await first; });
  it("marks cancelled responses stale", async () => { let resolveResponse: ((response: Response) => void) | undefined; const fetcher = vi.fn((_input: RequestInfo | URL, init?: RequestInit) => new Promise<Response>((resolve) => { resolveResponse = resolve; init?.signal?.addEventListener("abort", () => resolve(new Response(JSON.stringify(success)))); })); const controller = createFollowUpEvaluationRequestController(fetcher); const pending = controller.submit(buildFollowUpEvaluationRequest(validPreparation.questions[0], "A sufficiently detailed original interview answer.", history, "en", "continue")); controller.cancel(); resolveResponse?.(new Response(JSON.stringify(success))); expect(await pending).toEqual({ status: "stale" }); });
  it("does not automatically retry a failed request or call another endpoint", async () => { const fetcher = vi.fn().mockRejectedValueOnce(new Error("offline")); const controller = createFollowUpEvaluationRequestController(fetcher); const result = await controller.submit(buildFollowUpEvaluationRequest(validPreparation.questions[0], "A sufficiently detailed original interview answer.", history, "en", "continue")); expect(result.status).toBe("completed"); expect(fetcher).toHaveBeenCalledTimes(1); expect(fetcher.mock.calls[0]?.[0]).toBe("/api/interview/practice/follow-up/evaluate"); });
});
