import { describe, expect, it, vi } from "vitest";
import { validPreparation } from "@/test/preparationFixture";
import { validFinalEvaluation } from "@/test/followUpEvaluationFixture";
import { buildFollowUpEvaluationRequest, createFollowUpEvaluationRequestController } from "./followUpEvaluationClient";
const success = { success: true as const, data: { finalEvaluation: validFinalEvaluation } };
describe("follow-up evaluation client", () => {
  it("builds only allowlisted fields", () => { const payload = buildFollowUpEvaluationRequest(validPreparation.questions[0], "A sufficiently detailed original interview answer.", "What was the outcome?", "The issue stopped occurring after validation.", "en"); expect(Object.keys(payload).sort()).toEqual(["answerOutline", "category", "difficulty", "followUpAnswer", "followUpQuestion", "jdEvidence", "originalAnswer", "outputLanguage", "question", "relatedRequirement", "resumeEvidence", "whyAsked"].sort()); expect(payload).not.toHaveProperty("resume"); expect(payload).not.toHaveProperty("initialEvaluation"); });
  it("posts once and blocks a rapid duplicate", async () => { let resolveResponse: ((response: Response) => void) | undefined; const fetcher = vi.fn((input: RequestInfo | URL, init?: RequestInit) => new Promise<Response>((resolve) => { void input; void init; resolveResponse = resolve; })); const controller = createFollowUpEvaluationRequestController(fetcher); const payload = buildFollowUpEvaluationRequest(validPreparation.questions[0], "A sufficiently detailed original interview answer.", "What was the outcome?", "The issue stopped occurring after validation.", "en"); const first = controller.submit(payload); expect(await controller.submit(payload)).toEqual({ status: "duplicate" }); expect(fetcher).toHaveBeenCalledTimes(1); expect(fetcher.mock.calls[0]?.[0]).toBe("/api/interview/practice/follow-up/evaluate"); resolveResponse?.(new Response(JSON.stringify(success))); await first; });
  it("marks cancelled responses stale", async () => { let resolveResponse: ((response: Response) => void) | undefined; const fetcher = vi.fn((_input: RequestInfo | URL, init?: RequestInit) => new Promise<Response>((resolve) => { resolveResponse = resolve; init?.signal?.addEventListener("abort", () => resolve(new Response(JSON.stringify(success)))); })); const controller = createFollowUpEvaluationRequestController(fetcher); const payload = buildFollowUpEvaluationRequest(validPreparation.questions[0], "A sufficiently detailed original interview answer.", "What was the outcome?", "The issue stopped occurring after validation.", "en"); const pending = controller.submit(payload); controller.cancel(); resolveResponse?.(new Response(JSON.stringify(success))); expect(await pending).toEqual({ status: "stale" }); });
});
