import { beforeEach, describe, expect, it, vi } from "vitest";
import { AiNotConfiguredError } from "@/lib/ai/geminiClient";
import { FollowUpEvaluationAuthenticationError, FollowUpEvaluationEmptyOutputError, FollowUpEvaluationInvalidJsonError, FollowUpEvaluationInvalidOutputError, FollowUpEvaluationRateLimitedError, FollowUpEvaluationUpstreamError } from "@/lib/ai/evaluateInterviewFollowUp";
import { validFinalEvaluation, validFollowUpEvaluationRequest } from "@/test/followUpEvaluationFixture";
vi.mock("@/lib/ai/evaluateInterviewFollowUp", async (original) => ({ ...(await original<typeof import("@/lib/ai/evaluateInterviewFollowUp")>()), evaluateInterviewFollowUp: vi.fn() }));
import { evaluateInterviewFollowUp } from "@/lib/ai/evaluateInterviewFollowUp";
import { POST } from "./route";
const mocked = vi.mocked(evaluateInterviewFollowUp);
const request = (body: string, type = "application/json") => new Request("http://localhost/api/interview/practice/follow-up/evaluate", { method: "POST", headers: { "Content-Type": type }, body });
describe("follow-up evaluation route", () => {
  beforeEach(() => mocked.mockReset());
  it("rejects content type and malformed JSON", async () => { expect((await POST(request("x", "text/plain"))).status).toBe(415); expect((await POST(request("{"))).status).toBe(400); });
  it.each(["originalAnswer", "followUpQuestion", "followUpAnswer"] as const)("rejects missing %s", async (field) => { const value: Record<string, unknown> = { ...validFollowUpEvaluationRequest }; delete value[field]; expect((await POST(request(JSON.stringify(value)))).status).toBe(422); expect(mocked).not.toHaveBeenCalled(); });
  it("returns dedicated length errors", async () => { expect((await (await POST(request(JSON.stringify({ ...validFollowUpEvaluationRequest, followUpAnswer: "short" })))).json()).error.code).toBe("FOLLOW_UP_ANSWER_TOO_SHORT"); expect((await (await POST(request(JSON.stringify({ ...validFollowUpEvaluationRequest, followUpAnswer: "x".repeat(3001) })))).json()).error.code).toBe("FOLLOW_UP_ANSWER_TOO_LONG"); });
  it.each(["resume", "jobDescription", "analysis", "questions", "reviewTopics", "extractedText", "apiKey"])("rejects forbidden %s safely", async (field) => { const secret = "private-answer-resume-jd-prompt-key"; const response = await POST(request(JSON.stringify({ ...validFollowUpEvaluationRequest, [field]: secret }))); expect(response.status).toBe(422); expect(JSON.stringify(await response.json())).not.toContain(secret); });
  it("calls AI once and wraps finalEvaluation", async () => { mocked.mockResolvedValueOnce(validFinalEvaluation); const response = await POST(request(JSON.stringify(validFollowUpEvaluationRequest))); expect(await response.json()).toEqual({ success: true, data: { finalEvaluation: validFinalEvaluation } }); expect(mocked).toHaveBeenCalledTimes(1); });
  it.each([[new AiNotConfiguredError(), "AI_NOT_CONFIGURED", 503], [new FollowUpEvaluationAuthenticationError(), "AI_AUTHENTICATION_ERROR", 502], [new FollowUpEvaluationRateLimitedError(), "AI_RATE_LIMITED", 429], [new FollowUpEvaluationUpstreamError("raw secret"), "AI_UPSTREAM_ERROR", 502], [new FollowUpEvaluationEmptyOutputError(), "AI_EMPTY_OUTPUT", 502], [new FollowUpEvaluationInvalidJsonError(), "AI_INVALID_JSON", 502], [new FollowUpEvaluationInvalidOutputError(), "AI_INVALID_OUTPUT", 502]] as const)("maps safe error %#", async (error, code, status) => { mocked.mockRejectedValueOnce(error); const response = await POST(request(JSON.stringify(validFollowUpEvaluationRequest))); expect(response.status).toBe(status); const serialized = JSON.stringify(await response.json()); expect(serialized).toContain(code); expect(serialized).not.toContain(validFollowUpEvaluationRequest.followUpAnswer); expect(serialized).not.toContain("raw secret"); });
});
